
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BTN CHECKBOX EVAL INPUTFIELD INTEGER LABEL MSGBOX PRINTLN RELATIVE SHOW SIZE STRING TITLEprogram : statement\n               | program statementstatement : PRINTLN STRINGstatement : SIZE INTEGER INTEGERstatement : SHOWstatement : RELATIVE STRINGstatement : LABEL STRING INTEGER INTEGERstatement : TITLE STRINGstatement : EVAL STRINGstatement : BTN STRING INTEGER INTEGERstatement : MSGBOX STRING STRING STRING STRINGstatement : CHECKBOX STRING INTEGER INTEGERstatement : INPUTFIELD INTEGER INTEGER'
    
_lr_action_items = {'PRINTLN':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[3,3,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'SIZE':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[4,4,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'SHOW':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[5,5,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'RELATIVE':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[6,6,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'LABEL':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[7,7,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'TITLE':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[8,8,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'EVAL':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[9,9,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'BTN':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[10,10,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'MSGBOX':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[11,11,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'CHECKBOX':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[12,12,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'INPUTFIELD':([0,1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[13,13,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'$end':([1,2,5,14,15,17,19,20,25,30,31,32,34,35,],[0,-1,-5,-2,-3,-6,-8,-9,-4,-13,-7,-10,-12,-11,]),'STRING':([3,6,7,8,9,10,11,12,22,28,33,],[15,17,18,19,20,21,22,23,28,33,35,]),'INTEGER':([4,13,16,18,21,23,24,26,27,29,],[16,24,25,26,27,29,30,31,32,34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,1,],[2,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','parser.py',15),
  ('program -> program statement','program',2,'p_program','parser.py',16),
  ('statement -> PRINTLN STRING','statement',2,'p_statement_println','parser.py',19),
  ('statement -> SIZE INTEGER INTEGER','statement',3,'p_statement_setsize','parser.py',23),
  ('statement -> SHOW','statement',1,'p_statement_create','parser.py',27),
  ('statement -> RELATIVE STRING','statement',2,'p_statement_relative','parser.py',33),
  ('statement -> LABEL STRING INTEGER INTEGER','statement',4,'p_statement_label','parser.py',37),
  ('statement -> TITLE STRING','statement',2,'p_statement_title','parser.py',44),
  ('statement -> EVAL STRING','statement',2,'p_statement_eval','parser.py',48),
  ('statement -> BTN STRING INTEGER INTEGER','statement',4,'p_statement_btn','parser.py',52),
  ('statement -> MSGBOX STRING STRING STRING STRING','statement',5,'p_statement_msgbox','parser.py',56),
  ('statement -> CHECKBOX STRING INTEGER INTEGER','statement',4,'p_statement_checkbox','parser.py',60),
  ('statement -> INPUTFIELD INTEGER INTEGER','statement',3,'p_statement_inputfield','parser.py',65),
]
